language: node_js

node_js:
  - "4.1"

before_install:
  - "sh ./scripts/install.sh"

before_script:
  - "npm install -g grunt-cli"
  - "npm install -g mocha"
  - "npm install -g bower"
  - "gem install compass"

script: 
  - "sh ./scripts/test.sh"

deploy:
  provider: script
  script: scripts/deploy.sh
