language: node_js
node_js:
- '4.1'
before_install:
- npm install -g bower
- sh ./scripts/install.sh
before_script:
- npm install -g grunt-cli
- npm install -g mocha
- npm install -g istanbul
- gem install compass
script:
- sh ./scripts/test.sh
deploy:
  provider: script
  script: sh ./scripts/deploy.sh
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
