language: node_js

node_js:
  - "4.1"

before_script:
  - "npm install -g grunt"
  - "npm install -g mocha"

script: 
  - "grunt --base client --gruntfile client/GruntFile.js build --force"
  - "cd server && mocha"
